language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - python3  # Python 2.7 would also require the ipaddress backport
      - python3-dev
      - libssl-dev

branches:
  only:
  - master
  - topic/actor-system

before_script: ./configure --with-python=`which python3` && make -j4

script: make test
